# Generated by Django 5.2.5 on 2025-08-12 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('users', '0002_alter_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='userId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.user'),
            preserve_default=False,
        ),
    ]
