# Generated by Django 5.2.5 on 2025-08-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_address_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('casa', 'Casa'), ('trabajo', 'Trabajo'), ('edificio', 'Edificio')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
