# Generated by Django 5.2.5 on 2025-08-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_remove_address_country_remove_address_postal_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='address',
        ),
    ]
