# Generated by Django 5.2.5 on 2025-08-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_rename_street_address_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='Mi hogar', max_length=100),
            preserve_default=False,
        ),
    ]
