# Generated by Django 5.2.5 on 2025-11-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_address_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
    ]
