# Generated by Django 5.2.5 on 2025-08-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(blank=True, default="'user_'DVJjQufJHlM3", primary_key=True, serialize=False),
        ),
    ]
