# Generated by Django 5.2.5 on 2025-08-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_gender_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(blank=True, default="'user_'uMku8tRIURby", primary_key=True, serialize=False),
        ),
    ]
