# Generated by Django 5.2.5 on 2025-10-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_clerk_id_alter_user_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clerk_id',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(blank=True, default='user_VuVodpITKOL3', primary_key=True, serialize=False, unique=True),
        ),
    ]
