# Generated by Django 5.2.5 on 2025-11-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_userratingid_userrating_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(blank=True, default='user_XugiaiPYZWKn', primary_key=True, serialize=False, unique=True),
        ),
    ]
