# Generated by Django 5.2.5 on 2025-11-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(blank=True, default='user_IAAuB1kTR3pj', primary_key=True, serialize=False, unique=True),
        ),
    ]
