# Generated by Django 5.2.5 on 2025-11-15 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_userid'),
        ('vehicles', '0004_alter_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_drivers', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(blank=True, default='user_QXMktiiaStWQ', primary_key=True, serialize=False, unique=True),
        ),
    ]
