# Generated by Django 5.2.5 on 2025-11-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_current_vehicle_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(blank=True, default='user_rT9eLThwtftJ', primary_key=True, serialize=False, unique=True),
        ),
    ]
