# Generated by Django 5.2.5 on 2025-11-07 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('licensePlate', models.CharField(max_length=20, unique=True)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('color', models.CharField(max_length=30)),
                ('driverLicenseStatus', models.CharField(default='pending', max_length=20)),
                ('registrationCardStatus', models.CharField(default='pending', max_length=20)),
                ('insurancePolicyStatus', models.CharField(default='pending', max_length=20)),
                ('criminalRecordStatus', models.CharField(default='pending', max_length=20)),
                ('isVerified', models.BooleanField(default=False)),
                ('verificationNotes', models.TextField(blank=True, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
