# Generated by Django 5.2.5 on 2025-11-07 22:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_address_isfavorite'),
        ('deliveries', '0001_initial'),
        ('vehicles', '0003_alter_vehicle_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('estimated_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_size', models.CharField(blank=True, max_length=100, null=True)),
                ('client_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.deliverycategory')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_quotes', to=settings.AUTH_USER_MODEL)),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_quotes', to='addresses.address')),
                ('pickup_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_quotes', to='addresses.address')),
            ],
            options={
                'verbose_name': 'Cotización de Entrega',
                'verbose_name_plural': 'Cotizaciones de Entrega',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_delivery_time', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('expired', 'Expirada')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_offers', to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicletype')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='deliveries.deliveryquote')),
            ],
            options={
                'verbose_name': 'Oferta de Domiciliario',
                'verbose_name_plural': 'Ofertas de Domiciliario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deliveryquote',
            index=models.Index(fields=['status', 'expires_at'], name='deliveries__status_a5ab31_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryquote',
            index=models.Index(fields=['is_active'], name='deliveries__is_acti_2ae73a_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryoffer',
            index=models.Index(fields=['status', 'expires_at'], name='deliveries__status_ef73c0_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryoffer',
            index=models.Index(fields=['is_active'], name='deliveries__is_acti_2148ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryoffer',
            unique_together={('delivery_person', 'quote')},
        ),
    ]
