# Generated by Django 5.2.5 on 2025-11-08 01:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_address_isfavorite'),
        ('deliveries', '0002_deliveryquote_deliveryoffer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryquote',
            name='history_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('estimated_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_size', models.CharField(blank=True, max_length=100, null=True)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('picked_up', 'Recogido'), ('in_transit', 'En tránsito'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.deliverycategory')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_deliveries', to='addresses.address')),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL)),
                ('pickup_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_deliveries', to='addresses.address')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='deliveries.deliveryquote')),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='deliveries__status_bdfe1b_idx'), models.Index(fields=['client'], name='deliveries__client__5f82f7_idx'), models.Index(fields=['delivery_person'], name='deliveries__deliver_f6cb7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_id', models.UUIDField()),
                ('event_type', models.CharField(choices=[('quote_created', 'Cotización Creada'), ('offer_made', 'Oferta Realizada'), ('offer_accepted', 'Oferta Aceptada'), ('status_changed', 'Estado Cambiado'), ('cancelled', 'Cancelado'), ('completed', 'Completado')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_history_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Domicilio',
                'verbose_name_plural': 'Historiales de Domicilio',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['history_id'], name='deliveries__history_7d4257_idx'), models.Index(fields=['event_type'], name='deliveries__event_t_5a70b3_idx')],
            },
        ),
    ]
