# Generated by Django 5.2.5 on 2025-11-14 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_address_isfavorite'),
        ('deliveries', '0003_deliveryquote_history_id_delivery_deliveryhistory'),
        ('vehicles', '0004_alter_vehicle_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deliveryoffer',
            name='deliveries__status_ef73c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliveryoffer',
            name='deliveries__is_acti_2148ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliveryquote',
            name='deliveries__status_a5ab31_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliveryquote',
            name='deliveries__is_acti_2ae73a_idx',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='deliveryoffer',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='deliveryoffer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='deliveryquote',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='deliveryquote',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='deliveryquote',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='deliveryquote',
            name='delivery_address_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryquote',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryquote',
            name='payment_method',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryquote',
            name='pickup_address_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('assigned', 'Asignado'), ('picked_up', 'Recogido'), ('in_transit', 'En tránsito'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryquote',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_quotes', to='addresses.address'),
        ),
        migrations.AlterField(
            model_name='deliveryquote',
            name='pickup_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_quotes', to='addresses.address'),
        ),
        migrations.AlterField(
            model_name='deliveryquote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='deliveryoffer',
            index=models.Index(fields=['status'], name='deliveries__status_54bdef_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryquote',
            index=models.Index(fields=['status'], name='deliveries__status_408eb7_idx'),
        ),
    ]
