# Generated by Django 5.2.5 on 2025-11-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_remove_deliveryoffer_deliveries__status_ef73c0_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryquote',
            options={'ordering': ['-id'], 'verbose_name': 'Cotización de Entrega', 'verbose_name_plural': 'Cotizaciones de Entrega'},
        ),
        migrations.RemoveField(
            model_name='deliveryquote',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('assigned', 'Asignado'), ('picked_up', 'Recogido'), ('in_transit', 'En tránsito'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='assigned', max_length=20),
        ),
    ]
