# Generated by Django 5.2.5 on 2025-11-14 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_alter_deliveryquote_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryquote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cotización de Entrega', 'verbose_name_plural': 'Cotizaciones de Entrega'},
        ),
        migrations.AddField(
            model_name='deliveryquote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
