# Generated by Django 5.2.5 on 2025-11-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_alter_deliveryquote_options_deliveryquote_created_at'),
    ]

    operations = [
        # Renombrar campos de texto de direcciones en DeliveryQuote
        migrations.RenameField(
            model_name='deliveryquote',
            old_name='pickup_address_text',
            new_name='pickup_address',
        ),
        migrations.RenameField(
            model_name='deliveryquote',
            old_name='delivery_address_text',
            new_name='delivery_address',
        ),

        # Convertir direcciones a TextField
        migrations.AlterField(
            model_name='deliveryquote',
            name='pickup_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deliveryquote',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),

        # Cambiar observations a JSONField lista
        migrations.AlterField(
            model_name='deliveryquote',
            name='observations',
            field=models.JSONField(blank=True, default=list),
        ),

        # Cambiar direcciones en Delivery a TextField
        migrations.AlterField(
            model_name='delivery',
            name='pickup_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_address',
            field=models.TextField(),
        ),
    ]