# Generated by Django 5.2.5 on 2025-11-15 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_update_addresses_and_observations'),
        ('vehicles', '0004_alter_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryoffer',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='deliveryoffer',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle', related_name='delivery_offers'),
        ),
    ]
