# Generated by Django 5.2.5 on 2025-11-15 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_remove_deliveryoffer_vehicle_type_and_more'),
        ('vehicles', '0004_alter_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='vehicles.vehicle'),
        ),
    ]
