# Generated by Django 5.2.5 on 2025-11-20 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0009_delivery_vehicle'),
        ('vehicles', '0004_alter_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryquote',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicletype'),
        ),
    ]
