# Generated by Django 5.2.5 on 2025-11-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0011_deliveryquote_expires_at_deliveryoffer_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryquote',
            name='delivery_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='deliveryquote',
            name='pickup_address',
            field=models.TextField(),
        ),
    ]
