# Generated by Django 5.2.5 on 2025-11-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0012_alter_deliveryquote_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='observations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('assigned', 'Asignado'), ('picked_up', 'Recogido'), ('in_transit', 'En tránsito'), ('delivered', 'Entregado'), ('paid', 'Pagado'), ('cancelled', 'Cancelado')], default='assigned', max_length=20),
        ),
    ]
